version: '3'
services:
  khiemle_discord_bot:
    container_name: khiemle_discord_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    restart: always
    volumes:
      - ./logs:/app/logs
